### ISSUE TITLE
Render ui popup overlap with map 

### ISSUE THREAD

**Issue by hotrungnhan** [am2222/strapi-plugin-postgis#3]
![Screen Shot 2022-09-28 at 14 11 53](https://user-images.githubusercontent.com/40029631/192712405-23d44b95-ad0c-47d1-8ba8-035f64c485ac.png)
suggest : 
```css
.leaflet-container{
    z-index :0;
}

```
